name: CI/CD

# 只在手动触发时运行
on:
  workflow_dispatch:
    inputs:
      environment:
        description: '选择环境'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - staging
        - development
      debug:
        description: '是否开启调试模式'
        required: false
        type: boolean
        default: false

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
      
      - name: 设置 pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      
      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
      
      - name: 安装依赖
        run: |
          pnpm install --no-frozen-lockfile
      
      - name: 构建
        run: pnpm build
        env:
          NODE_ENV: ${{ github.event.inputs.environment }}
      
      - name: 上传构建产物
        uses: actions/upload-artifact@v3
        with:
          name: dist-${{ github.event.inputs.environment }}
          path: |
            dist/
            release/