name: CI/CD

on:
  workflow_dispatch:
    inputs:
      version:
        description: '版本号 (例如: 1.0.2)'
        required: true
        type: string
      environment:
        description: '选择环境'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - staging
        - development

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
      
      # 首先设置 pnpm
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      
      # 然后设置 Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
      
      # 安装依赖
      - name: 安装依赖
        run: pnpm install --frozen-lockfile
      
      # 构建
      - name: 构建
        run: pnpm build
        env:
          NODE_ENV: ${{ github.event.inputs.environment }}
      
      # 创建 Release
      - name: 创建 Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: Release v${{ github.event.inputs.version }}
          files: |
            dist/*.upx
            release/**/*.exe
            release/**/*.dmg
            release/**/*.AppImage
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}