name: CI/CD

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      debug:
        description: '是否开启调试模式'
        required: false
        type: boolean
        default: false

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
      
      - name: 设置 pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      
      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
      
      - name: 清理 pnpm 存储
        run: |
          pnpm store path
          pnpm store prune
          rm -rf node_modules
          rm -f pnpm-lock.yaml
      
      - name: 安装依赖
        run: |
          pnpm install --force
      
      - name: 类型检查
        run: pnpm run vue-tsc --noEmit || true
      
      - name: 构建
        run: pnpm build
      
      - name: 上传构建产物
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            dist/
            release/